"""Tests for scripts/codex-agents: the stage agents as Codex agent tomls.

Run from the plugin dir:  python3 -m unittest discover -s tests -v
"""

import os
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GEN = os.path.join(ROOT, "scripts", "codex-agents")


def parse_toml(text):
    """Enough TOML for the generated files: `key = "str"` and `key = '''...'''`."""
    out, lines, i = {}, text.splitlines(), 0
    while i < len(lines):
        line = lines[i]
        i += 1
        if not line.strip() or line.startswith("#"):
            continue
        key, _, val = line.partition(" = ")
        if val == "'''":
            body = []
            while lines[i] != "'''":
                body.append(lines[i])
                i += 1
            i += 1
            out[key] = "\n".join(body)
        else:
            import json
            out[key] = json.loads(val)
    return out


AGENTS = ("implementor", "reporter", "reviewer", "test_writer", "verifier")
TIERS = {"light": "gpt-6-luna", "standard": "gpt-6.1-sol", "heavy": "gpt-6-astra",
         "frontier": "gpt-6-astra"}
EFFORTS = ("low", "high")


class CodexAgentsTests(unittest.TestCase):
    def generate(self, out=None):
        out = out or tempfile.mkdtemp()
        self.addCleanup(lambda: subprocess.run(["rm", "-rf", out]))
        p = subprocess.run([sys.executable, GEN, "--out", out], capture_output=True,
                           text=True)
        self.assertEqual(p.returncode, 0, p.stderr)
        agents = {}
        for n in sorted(os.listdir(out)):
            with open(os.path.join(out, n)) as f:
                agents[n] = parse_toml(f.read())
        return out, agents

    def test_one_toml_per_stage_agent_tier_and_effort(self):
        _, agents = self.generate()
        self.assertEqual(sorted(agents), sorted(
            "%s_%s_%s.toml" % (a, t, e) for a in AGENTS for t in TIERS for e in EFFORTS))
        self.assertEqual(agents["test_writer_heavy_high.toml"]["name"],
                         "test-writer-heavy-high")

    def test_each_tier_sets_its_model_and_each_rung_its_effort(self):
        _, a = self.generate()
        for agent in AGENTS:
            for tier, model in TIERS.items():
                for effort in EFFORTS:
                    t = a["%s_%s_%s.toml" % (agent, tier, effort)]
                    self.assertEqual((t["model"], t["model_reasoning_effort"]),
                                     (model, effort), (agent, tier, effort))

    def test_sandbox_follows_the_tools(self):
        _, a = self.generate()
        for tier in TIERS:
            self.assertEqual(a["reviewer_%s_low.toml" % tier]["sandbox_mode"], "read-only")
            # The verifier inherits the session's sandbox: it drives a browser.
            self.assertNotIn("sandbox_mode", a["verifier_%s_low.toml" % tier])
            for n in ("test_writer", "implementor", "reporter"):
                self.assertEqual(a["%s_%s_low.toml" % (n, tier)]["sandbox_mode"],
                                 "workspace-write")

    def test_stale_untiered_and_tier_only_files_are_removed(self):
        out = tempfile.mkdtemp()
        for n in ("implementor.toml", "test_writer.toml", "implementor_heavy.toml"):
            with open(os.path.join(out, n), "w") as f:
                f.write('# Generated by orchestration/scripts/codex-agents from x\n'
                        'name = "old"\n')
        # A user's own files, including one named like a stage agent, survive.
        for n in ("mine.toml", "reviewer.toml"):
            with open(os.path.join(out, n), "w") as f:
                f.write('name = "%s"\n' % n[:-5])
        _, agents = self.generate(out)
        self.assertNotIn("implementor.toml", agents)
        self.assertNotIn("test_writer.toml", agents)
        self.assertNotIn("implementor_heavy.toml", agents)
        self.assertIn("mine.toml", agents)
        self.assertEqual(agents["reviewer.toml"]["name"], "reviewer")

    def test_stage_agents_pin_no_model_and_no_effort(self):
        for n in sorted(os.listdir(os.path.join(ROOT, "agents"))):
            if n.endswith(".md"):
                with open(os.path.join(ROOT, "agents", n)) as f:
                    fm = f.read().split("---", 2)[1]
                self.assertNotRegex(fm, r"(?m)^model:", n)
                self.assertNotRegex(fm, r"(?m)^effort:", n)

    def test_instructions_are_the_agent_body(self):
        _, a = self.generate()
        with open(os.path.join(ROOT, "agents", "reviewer.md")) as f:
            body = f.read().split("---", 2)[2]
        self.assertEqual(a["reviewer_light_low.toml"]["developer_instructions"], body.strip())
        self.assertIn("orchestration pipeline", a["reviewer_light_low.toml"]["description"])


if __name__ == "__main__":
    unittest.main()
